apiVersion: v1
kind: Service
metadata:
  name: {{ include "fusionauth.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fusionauth.name" . }}
    helm.sh/chart: {{ include "fusionauth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations -}}
  annotations:
{{ .Values.service.annotations | toYaml | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "fusionauth.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ .Values.service.spec | toYaml | indent 2 }}